.github/dependabot.yml
This adds github actions checks to dependabot weekly updtes
=> Update dependabot to include github actions

.gitignore, README.md
Updated some of the text in the README to include references
to the new usage doc and be a little clearer.
Also updated .gitignore to skip mac filesystem turds
=> README updates, plus a gitignore tweak

.env.example, README.md, docs/using-the-app.md
Made the example `.env` a bit more verbose and reordered
the deployment section of the readme. Maybe needs more?
=> Quick doc updates to reflect new auth improvements

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/pull_request-template.md
=> docs: add github issue templates

package-lock.json, package.json, src/bot/graphql.ts, src/bot/index.ts, src/bot/rules.ts, src/pages/orgs/[organizationId]/forks/[forkId].tsx, src/server/routers/repos.ts, src/types/underscore.d.ts, src/utils/logger.ts, test/app.test.ts
- Adds searching for repo by description as well as props
- Fall back to use branch protections if repo rulesets fail to create
=> feat: add fallback methods for branch protection and repo description

.github/pull_request_template.md, .github/release-drafter.yml, .github/workflows/auto-labeler.yml, .github/workflows/docker-build.yml, .github/workflows/lint.yml, .github/workflows/pr-title.yml, .github/workflows/release.yml, .github/workflows/tests.yml
=> feat: automated releases and auto labelling

.github/release-drafter.yml, .github/workflows/release.yml
=> fix: url in release notes and drop discussions creation

src/app/api/auth/lib/nextauth-options.ts, src/app/context/AuthProvider.tsx, src/app/layout.tsx, src/types/next-auth.d.ts
- Fixes #118 
- Adds ability to refresh access token after 8 hour expiration
=> feat: refresh access token on expiration

src/app/[organizationId]/forks/[forkId]/page.tsx, src/app/[organizationId]/layout.tsx, src/app/[organizationId]/page.tsx, src/app/auth/login/page.tsx, src/app/components/breadcrumbs/OrgBreadcrumbs.tsx, src/app/components/header/ForkHeader.tsx, src/app/components/header/WelcomeHeader.tsx, src/app/components/search/Search.tsx, src/app/components/search/SearchWithCreate.tsx, src/app/context/AuthProvider.tsx, src/app/layout.tsx, src/app/page.tsx, src/hooks/useFork.tsx, src/hooks/useOrganization.tsx, src/hooks/useOrganizations.tsx
- Closes #130 
- add selection page for org
- make search components generic
- separate welcome, org, and fork headers
- add orgs hook
=> feat: add org selection page

src/app/api/auth/lib/nextauth-options.ts, src/app/context/AuthProvider.tsx, src/bot/config.ts, src/bot/rules.ts, src/server/octokit/controller.ts, src/server/repos/controller.ts, src/utils/logger.ts
- Closes #129
- update tslog json transport to spit out proper json
- sanitize log message in some places
- add additional secret mask regex values
Due to numerous limitations with both pino (doesn't work with next.js) and winston (doesn't support log traces, difficult formatting, having to do `new Error()` to display error stack), we are sticking with tslog, but have made changes to the JSON transport to allow better parsing in splunk.
=> feat: update tslog

src/app/[organizationId]/forks/[forkId]/page.tsx, src/app/[organizationId]/page.tsx, src/app/page.tsx, src/hooks/useFork.tsx, src/hooks/useForks.tsx, src/hooks/useOrganization.tsx
- Closes #155 
- Adds loading and error state to all hooks
- Displays loading table only while data is fetching
- Displays empty table (with error message if necessary) if there is no data
=> fix: improve hooks to show loading/error table

src/server/repos/controller.ts
- Fixes an issue caused by removing the try/catch around the exists call
=> fix: add catch handling for already exists

README.md
The screenshot still had the old name
=> docs: Update README.md with new screenshot

.env.example, env.mjs, src/app/api/auth/lib/nextauth-options.ts, src/server/repos/controller.ts, src/utils/logger.ts
- Adds minimum level to logger to hide debug logs in production
- Removes string interpolation from some logs for easier Splunk capture
- Adds mirror created log for Splunk
=> fix: add min level to logger

README.md
Missed this one in the previous update
Relates to #197
=> docs: Update one more screenshot to change ICF->PMA

README.md
The previous link went to an older video, not the nice new one.
- n/a  If publishing new data to the public (scorecards, security scan results, code quality results, live dashboards, etc.), please request review from `@jeffrey-luszcz`
=> docs: Update youtube link to final video

CODEOWNERS
=> feat: add pma-maintainers to codeowners

.gitignore, next-env.d.ts
Add next-env.d.ts to the gitignore file since it is autogenerated by next and should not be edited. This came up because next changed a reference link in that file and caused it to appear in the git's changed files.
=> chore: gitignore generated next-env types

src/app/api/auth/lib/nextauth-options.ts, src/bot/index.ts, src/types/forks.ts, src/utils/logger.ts
I've been inconsistently encountering some eslint issues that I figured I'd just fix to resolve the problem. The inconsistency is likely due to dependency compatibility between installed patch versions.
The lint issues in question include:
- unused variables due to a catch block with an error variable that isn't referenced (src/app/api/auth/lib/nextauth-options.ts, src/bot/index.ts, src/utils/logger.ts)
- variable is assigned a value but only used as a type (src/types/forks.ts), this is a weird one which I resolved by making the variable name match the type name which is done elsewhere in `src/bot/rest.ts`
- using `Object.prototype.hasOwnProperty.call` when `Object.hasOwn` is recommended (src/utils/logger.ts)
- using `||` when `??` is recommended (src/utils/logger.ts)
- using `{ [key: …
=> fix: resolve inconsistent eslint issues

Dockerfile
=> feat: add labels to dockerfile

package-lock.json, package.json
=> fix(deps): update next to 14.2.25

.github/workflows/docker-build.yml, Dockerfile
Use Docker Actions for building the `private-mirrors` image. This includes some caching benefits, reproducible builds, build summary for helpful info and debugging, and configuration checks.
Note: I configured this using the GitHub Actions cache for Docker, which is experimental. If this gives us trouble, we can disable the cache. See https://docs.docker.com/build/ci/github-actions/cache/#github-cache for details. The initial build took much longer (~4x longer), but a subsequent build with the cache was much quicker (~4x quicker).
=> ci: use docker actions

.github/workflows/build.yml, .github/workflows/docker-build.yml, .github/workflows/lint.yml, .github/workflows/tests.yml
Add permissions to actions workflows where missing
=> fix: add permissions to actions workflows where missing

package-lock.json, package.json, src/bot/index.ts, test/bot/index.test.ts
This PR adds logic to sync changes to the fork branch back to the default branch on the mirror.
Closes https://github.com/github-community-projects/private-mirrors/issues/378
=> feat: add logic to sync fork changes back to mirror
