- CODEOWNERS
This makes the github ospo team to be the proper owners of the ICF repo
> Update CODEOWNERS to be the ospo team

- next.config.mjs
- package-lock.json
- package.json
- src/bot/config.ts
- src/bot/octokit.ts
- src/bot/rest.ts
- src/env.mjs
- src/pages/orgs/[organizationId]/forks/[forkId].tsx
- src/server/routers/_app.ts
- src/server/routers/git.ts
- src/server/routers/repos.ts
- test/config.test.ts
- test/octomock/index.ts
- test/server/git.test.ts
This adds the ability to specify a different organization to hold mirrors into. This change requires the idea of a configuration to make this viable. This is done is a couple ways: through the `PUBLIC_ORG` and `PRIVATE_ORG` env variables, with a config file located in the public org's .github folder, or just not configuring it at all. 
Everything will still work as before. 
This also adds env file checking at runtime and throws an error when there is a misconfiguration
addresses #12
Documentation will be a follow up PR as no breaking changes are being introduced and all code is backwards compatible
> Add support for EMU workflows

- README.md
- docs/architecture.md
This updates the docs to let users know that we now support GHEC and how to use it.
We will need to eventually update the docs with a demo and complete setup guide.
> Update docs to include information about GHEC integration

- .env.example
- env.mjs
- src/pages/api/auth/[...nextauth].ts
- src/pages/api/trpc/[trpc].ts
- src/server/lib/auth.ts
- src/server/middleware/auth.ts
- src/server/routers/_app.ts
- src/server/routers/health.ts
- src/server/trpc.ts
- src/types/next-auth.d.ts
- test/octomock/index.ts
- test/server/auth.test.ts
- test/server/git.test.ts
- test/utils/auth.ts
This adds a middleware for verifying sessions for all of the routes in the server. 
This also adds an env configuration called `ALLOWED_HANDLES` which is a comma separated list of handles you want to restrict access to
> Add authentication middleware for routes and ALLOWED_HANDLES restrictions

- README.md
We renamed the manifest link a while back, need to update the readme to fix that.
fixes #65
> Update readme to fix app manifest link

- src/pages/api/webhooks.ts
This fixes an issue when we upgraded to probot 13
fixes https://github.com/github-community-projects/internal-contribution-forks/issues/88
> Disable payload parsing on webhook endpoint

- src/server/routers/git.ts
- test/server/git.test.ts
Since switching to a dual tenant model, we need to be explicit about which repo we want to delete on mirror creation failures. This fixes that.
> fix: cleanup the private mirror if it fails to create

- .env.example
- README.md
- env.mjs
- package-lock.json
- package.json
- scripts/probot-forwarder.js
- scripts/webhook-relay.mjs
This gets rid of smee as the preferred local webhook client. This does not require a webhook url anymore in the env but does require setting `PUBLIC_ORG`
This fixes #100
> feat: swap out smee with homegrown proxy client

- src/server/routers/git.ts
Adds a config option to Simple Git which disables the running of global git hooks which may be triggered when running ICF locally. In some testing of the app, unrelated git hooks on my machine caused failures in the app which can be avoided using this flag.
> fix: Disable Global Git Hooks in Simple Git

- .github/dependabot.yml
If grouping doesn't reduce PR spam we'll look at limiting npm and docker dependencies to only security updates
- [docs](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#:~:text=If%20you%20only%20require%20security%20updates%20and%20want%20to%20exclude%20version%20updates%2C%20you%20can%20set%20open%2Dpull%2Drequests%2Dlimit%20to%200%20in%20order%20to%20prevent%20version%20updates%20for%20a%20given%20package%2Decosystem.)
> chore: change from only security updates to grouping 

- src/server/git/router.ts
- src/utils/auth.ts
- src/utils/trpc-middleware.ts
- src/utils/trpc-server.ts
There was a missing `await` that caused a race condition in our trpc auth middleware. We would throw an authorization error _after_ we already called `next` on the middleware. 
This corrects that and fixes the auth.
> fix: middleware race condition when checking auth validity

- .eslintrc.json
- package-lock.json
- package.json
- src/app/[organizationId]/forks/[forkId]/page.tsx
- src/app/api/auth/[...nextauth]/route.tsx
- src/app/api/auth/lib/nextauth-options.ts
- src/app/api/trpc/trpc-router.ts
- src/app/components/flash/AppNotInstalledFlash.tsx
- src/app/components/header/MainHeader.tsx
- src/app/components/header/WelcomeHeader.tsx
- src/app/context/AuthProvider.tsx
- src/bot/config.ts
- src/bot/index.ts
- src/bot/octokit.ts
- src/hooks/useFork.tsx
- src/hooks/useForks.tsx
- src/hooks/useOrganization.tsx
- src/hooks/useOrganizations.tsx
- src/pages/api/webhooks.ts
- src/utils/auth.ts
- src/utils/logger.ts
While we were pairing on https://github.com/github-community-projects/internal-contribution-forks/pull/162, we found that we didn't add an `await` keyword to the function running the auth check. To prevent this from happening in the future, I added stricter eslint rules for typescript
This also fixes all the problems that arise from the addition of these rules. In general, we're looking pretty good 🥨
> feat: add stricter eslint rules for typescript

- .github/workflows/auto-labeler.yml
- .github/workflows/build.yml
- .github/workflows/docker-build.yml
- .github/workflows/lint.yml
- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
This pull request pins the versions of GitHub actions used in the project's workflows. The versions of these actions have been pinned to specific commits for increased stability and security. Version tags can be moved and create unpredictable results, so pinning to a specific commit ensures that the same version of the action is used every time the workflow runs.
> chore: Pin actions to SHAs for security and reproducibility

- package-lock.json
- package.json
- src/utils/logger.ts
`console.log` makes object appear on multiple lines. This adds support for a single line to be picked up by json by using stringify
> fix: stringify json logging to be single line

- .dockerignore
- Dockerfile
- docker-compose.yml
- we use a multi-stage build to install and use node_modules in the container
```shell
docker build -t icf
docker run --it --rm --env_file .env -p 3000:3000 --name icf icf:latest
```
```shell
docker-compose up -d
```
> chore: local dev fixes

- src/app/components/dialog/CreateMirrorDialog.tsx
- src/app/components/dialog/EditMirrorDialog.tsx
- src/server/repos/schema.ts
- test/server/repos.test.ts
fixes #135
This pull request limits the length of repository names in the application. The changes ensure that both the creation and editing of mirrors enforce a maximum length of 100 characters for the repository name. This is achieved through changes in the frontend and backend validation schemas.
- I want to add tests but wasn't able to find where we are already testing the mirror creation process. Is there a good spot to add a test for this? Maybe `test/app.test.ts`?
- Did I miss any spots that also need the limit enforced?
> fix: Enforce repository name length limit in dialogs

- src/app/components/dialog/EditMirrorDialog.tsx
fixes #136 
Updates the 'Edit mirror' dialog to display the current mirror name instead of the placeholder text 'repository-name'.
- Changes the initial state of `newMirrorName` to use the `mirrorName` prop, ensuring the current mirror name is displayed when the dialog opens.
- Updates the placeholder in the `TextInput` component to display the current mirror name, enhancing user experience by showing relevant information.
- Adjusts the logic for resetting `newMirrorName` upon dialog actions (cancel, confirm, close) to revert to the current mirror name instead of the placeholder, maintaining consistency with the initial state change.
> fix: edit mirror dialog to display current mirror name

- src/app/[organizationId]/forks/[forkId]/page.tsx
- src/app/[organizationId]/page.tsx
- src/app/layout.tsx
- src/app/page.tsx
- Closes #138
- increase items per page
- fix issue where body scrolled over header
- fix issue with pagination count and search
- due to limitations with primer table pagination, there is no way to fix the count when the 
last item on a table page is deleted, so when we run into this situation, reload the page
> fix: pagination issues

- src/app/[organizationId]/forks/[forkId]/page.tsx
- src/app/api/trpc/trpc-router.ts
- src/app/components/dialog/DeleteMirrorDialog.tsx
- src/server/config/controller.ts
- src/server/config/router.ts
- src/server/config/schema.ts
- test/server/config.test.ts
- Closes #137 
- Add api call to fetch config
- Use private org for orgLogin when set
- Show error flash when config fails to load
- Remove orgName from deleteMirror flash
> fix: use private org for location when set

- src/app/[organizationId]/forks/[forkId]/page.tsx
- src/app/components/flash/SuccessFlash.tsx
- src/server/repos/controller.ts
- src/server/repos/schema.ts
- Closes #128 
- Add error messages to error flashes
- Display error messages if error when creating, editing, and deleting mirrors
> feat: add error messages to error flashes

- src/bot/index.ts
Adds the proxy import to the webhook entrypoint to fix proxy issues that were encountered when running the webhooks independently of the UI. Related to https://github.com/github-community-projects/internal-contribution-forks/pull/134.
> fix: add proxy import to webhook entrypoint

- .github/ISSUE_TEMPLATE/config.yml
- .github/release-drafter.yml
- CONTRIBUTING.md
- README.md
- SUPPORT.md
- app.yml
- docs/using-the-app.md
This commit adjusts all the URL references to the new repo name,
and fixes text strings that refer to ICF to instead say PMA.
I did not address any references in *ts code.
Relates to #197
> docs: Rename docs and string references from ICF to PMA

- docs/using-the-app.md
Document security considerations for contributions through PMA once they are synced to a public fork.
> docs: add guidance on security implications for forks

- .github/workflows/scorecard.yml
Fix the version number in the comment for the `github/codeql-action/upload-sarif` GitHub Action. See https://github.com/github-community-projects/private-mirrors/pull/269 where this was not bumped properly and https://github.com/github-community-projects/private-mirrors/pull/269#issuecomment-2495557174 for a potential reason (the version in the comment being out of date). Hopefully this will fix the dependabot updates going forward to properly update the comment.
> chore: fix version comment for codeql action

- .github/release-drafter.yml
- .github/workflows/auto-labeler.yml
- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- will generate a release image called privoate-mirrors in ghcr.io with release tag and latest tag
- might replace https://github.com/github-community-projects/private-mirrors/pull/238 (digest work there can be added)
> feat: start using github/ospo-reusable-workflows

- src/bot/index.ts
Our team has been facing issues with syncing not working on our deployed version of private-mirrors. Everything works locally but when deployed the syncing fails with a TRPCClientError that has no further details. Every other feature of private-mirrors is working from what we can tell and we are unsure if this issue may be affecting other private-mirrors installations. Through investigation, we attempted to get any meaningful error or debug log output but were unable to get anything helpful. 
After taking a more in depth look at the implementation, we noticed that the sync functionality was the only trpc call made from the server rather than from a client browser and it seemed that there isn't much benefit to calling the sync function this way. Instead, there is added complexity by going …
> fix: simplify syncRepos call in push to resolve trpc issue

- package-lock.json
- package.json
Override `@octokit/plugin-paginate-rest` to a non-vulnerable version. The latest v3 Octokit version the project is using does not have an updated version to use. Also, apply non-breaking audit fixes.
I have opened https://github.com/github-community-projects/private-mirrors/issues/329 to track updating to Octokit v4 and included removing `overrides` added here as part of that work.
> fix(deps): update and override vulnerable dependencies

- docs/developing.md
- package-lock.json
- package.json
Closes https://github.com/github-community-projects/private-mirrors/issues/334.
- Only officially support LTS Node.js versions.
- Drop support for non-LTS versions greater than 18. Before non-LTS versions >18 that are EOL were allowed with the engines defined.
- List supported Node.js and npm versions for development. I kept these flexible to support the npm version bundled with Node.js and the latest version, and the supported Node.js versions. We could choose to only support Node.js 22 for development.
> chore: specify supported lts node.js versions

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/tests.yml
Use the [setup-node action](https://github.com/actions/setup-node) for Node.js workflows. Closes #335.
Also uses `npm ci` for dependency installs in CI and ignores scripts during install, both recommended best practices for improving security of the supply chain.
> ci: use setup-node action

- .github/workflows/build.yml
- .github/workflows/docker-build.yml
- .github/workflows/lint.yml
- .github/workflows/tests.yml
Do not persist git credentials in workflows that checkout code. This improves security for the workflows.
> ci: do not persist git credentials in workflows

- .env.example
- docs/developing.md
- scripts/webhook-relay.mjs
- src/bot/octokit.ts
- test/app.test.ts
- test/server/config.test.ts
This change adds support for a base64 encoded private key which helps to avoid issues with retrieving, setting, and passing around an environment variable value that contains newlines which may be required for some enterprise secret management strategies. The base64 parsing was made conditional to avoid breaking existing setups while allowing the option for those that might need it.
> feat: add base64 encoded private key support

- src/server/git/controller.ts
- test/server/git/controller.test.ts
This PR changes the repo sync logic. Instead of using merge, it will now use rebase.
https://github.com/github-community-projects/private-mirrors/issues/368 addresses the bugs that arise from using merges and the need for rebases.
> feat: use rebase when syncing changes from mirror/main back to fork

- src/bot/index.ts
- src/server/git/controller.ts
- test/server/git/controller.test.ts
This change fixes an issue that can arise with the logic to filter out bot pushes where automated pushes from other applications will not be synced. It is still necessary to filter out private mirrors pushes to avoid infinite looping with the sync back logic so a check was added to the syncReposHandler to see if the two branches' head shas already match.
> fix: issue with skipping bot pushes

- .env.example
- env.mjs
- src/server/repos/controller.ts
- test/server/repos.test.ts
This change adds an environment variable that allows for mirrors to be created with internal visibility for use in GHEC deployments. The internal visibility still ensures that only enterprise members can see the mirrors but makes it so that all enterprise members can see the mirrors.
> feat: support creating internal mirrors
